### ISSUE TITLE
email composer needs 'app' and isAvailable always false.

### ISSUE THREAD

**Issue by DocJump17** [katzer/cordova-plugin-email-composer#225]
I installed cordova email plugin usng the cli. I am using Android 7 with cordova 6.2.0 with phonegap and javascript. My environment is Windows XP with a Samsung Galaxy S6 Edge. I am testing on this android device directly. I have tested it extensively and found that 1)isAvailable always returns false and 2) email always fails to send unless 'app' is specified. "app" is mentioned in the documentation but there is no mention of it being required. Perhaps a clarification in the documentation is necessary. My main concern is that the email composer won't work if the 'app' parameter is specified but doesn't exist on the android device. Regards.

**Comment by hunnysharma102** [comment]
The thing is if you check the code for android. IsAvaialble checking two things.
1. If you have configured the default mail client.
2. If there is any application which support mail service.


And it return both two values isPossible , withSchema respectively.

So it should work if you have configured default mail client.

I fixed this according to my need you can find it
https://github.com/hunnysharma102/cordova-plugin-email-composer.git

**Comment by DocJump17** [comment]
Thank you for that information. I'm hoping you can answer a question for me regarding the required specification of attachments in an email using email composer. 
I am using a file name called '/docj.txt'  for creating and writing, but I cannot figure out what email composer needs in the attachment section in order to find and send the correct file. I've tried 'file://docj.txt', 'file:///docj.txt' and 'docj.txt and none work. Thanks for your help. '
George

----- Original Message -----

**Comment by voodoodrul** [comment]
I think this issue is back. I was successfully using this until Android 7.1.1. With no changes in my application, it now returns false again.

**Comment by katzer** [comment]
@DocJump17 It depend on where '/docj.txt' is located.
The sample app demonstrates how to use attachments!
