### ISSUE TITLE
The 'mailto' URI Scheme (RFC 2368) does not support attachments.

### ISSUE THREAD

**Issue by dylanvdmerwe** [katzer/cordova-plugin-email-composer#291]
I appear to be running into the error here: https://github.com/katzer/cordova-plugin-email-composer/blob/921d6a118ab36e7787ee9218b940e77863f5b512/src/ios/APPEmailComposerImpl.m#L151

![image](https://user-images.githubusercontent.com/2852839/35828241-7d748540-0ac7-11e8-9f2b-e2bb06199381.png)

Why am I not allowed to add file:/// attachments on iOS?

Plugin version: 0.8.14

**Comment by dylanvdmerwe** [comment]
This is not a problem in 0.8.13.

**Comment by katzer** [comment]
Unfortunately v0.8.14 had some bugs with mail scheme and attachments. Should work now again.

**Comment by kiran-ghuge** [comment]
Hi @dylanvdmerwe 
have you solved it.
I have same problem attaching file to email

**Comment by tobikummer** [comment]
same here, using outlook.
config is
 ```
let email = {
            app: 'outlook',
            attachments: ["file:///pathToFile1.pdf","file:///pathToFile2.pdf"],
            subject: emailSubject,
            body: emailBody,
            isHtml: true
        };
```
if I remove the "app"-line, iPad opens Apple Mail and it works fine. But we need do it in Outlook...

**Comment by katzer** [comment]
Have you extend the `*-Info.plist` to grant permission to communicate with the outlook app?

**Comment by tobikummer** [comment]
Outlook opens, even I don't extend the *-Info.plist. But the [error stills alive](https://github.com/katzer/cordova-plugin-email-composer/issues/338)

**Comment by katzer** [comment]
What error? Isn't the log message pretty clear? Attachments only work with iMail.

**Comment by samulla** [comment]
> same here, using outlook.
> config is
> 
> ```
> let email = {
>            app: 'outlook',
>            attachments: ["file:///pathToFile1.pdf","file:///pathToFile2.pdf"],
>            subject: emailSubject,
>            body: emailBody,
>            isHtml: true
>        };
> ```
> 
> if I remove the "app"-line, iPad opens Apple Mail and it works fine. But we need do it in Outlook...
> Use 0.8.15

Wer you able to resolve this? i have the same requirement, any help would be appreciated
